# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hellomate < Formula
  desc ""
  homepage "https://github.com/samlhuillier/homebrew-tools"
  version "1.0.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/samlhuillier/hellomate/releases/download/1.0.7/hellomate_1.0.7_Darwin_arm64.tar.gz"
      sha256 "6828cf586fac0c2edcaa22420554e7ad22916906028a07a3affe93ecadffbbbf"

      def install
        bin.install "hellomate"
        generate_completions_from_executable(bin/"hellomate", "completion zsh")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/samlhuillier/hellomate/releases/download/1.0.7/hellomate_1.0.7_Darwin_x86_64.tar.gz"
      sha256 "279b93b1a6e5b6a5f420fd65265e3001ff1efb1fede41b069a3c1405135a6704"

      def install
        bin.install "hellomate"
        generate_completions_from_executable(bin/"hellomate", "completion zsh")
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samlhuillier/hellomate/releases/download/1.0.7/hellomate_1.0.7_Linux_arm64.tar.gz"
      sha256 "d94c0a6d6ee0f11f04fa8fb10b3f341cb968486689255acf5cf856e2d4f47516"

      def install
        bin.install "hellomate"
        generate_completions_from_executable(bin/"hellomate", "completion zsh")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/samlhuillier/hellomate/releases/download/1.0.7/hellomate_1.0.7_Linux_x86_64.tar.gz"
      sha256 "7ccf4f1230274faaeef7b4380ff0fdc13ed133edc6e0432e107ea8348dab6266"

      def install
        bin.install "hellomate"
        generate_completions_from_executable(bin/"hellomate", "completion zsh")
      end
    end
  end
end
